"""
Interval-arithmetic evaluation of D and its derivatives to order six, for PROVED bounds. 2026-09-06.

Why. The certificate (q32_certificate_v2.py) is an inequality argument whose constants M2 = max|D''| and
M3 = max|D'''| on each subinterval are sampled maxima, which the independent audit flagged and Amendment 68 states as
the remaining limit. mpmath's iv context evaluates every operation with directed rounding, so an expression
evaluated on an interval X returns an interval containing the value at every x in X.

Closed forms. With L(x,y) = y log x - x - log y!, P = exp L, g = L - log Q(y), u = y/x:
    D^(n)(x) = sum_y P(x,y) h_n(u, x) g(x,y) + c_n(x),
    h_0 = 1,  h_{n+1} = dh_n/dx + h_n (u - 1),  c_{n+1} = E_x[h_n (U - 1)] + dc_n/dx  (U ~ Poisson(x)).
The first three are the ones used since support_mp3 (h_1 = u - 1, h_2 = (u-1)^2 - u/x, c_2 = 1/x). The
recurrence was run symbolically (sympy, Touchard moments E[Y^k] = sum_j S(k,j) x^j for the expectation) and
the resulting coefficient tables are hard-coded below as h_n = sum coef u^i / x^j; the control block
regenerates them from the recurrence and compares, and checks each closed form against a central difference
of the previous one. Those are the computations that could refute the tables. c_n = (-1)^n (n-2)!/x^(n-1).

Enclosures. The naive interval sum over-estimates the range by an amount LINEAR in the width h (0.29 h for
D'' at x = 20). The centered form  f(X) subset f(m) + f'(X) [-h/2, h/2]  is rigorous by the mean-value theorem
and over-estimates at order h^2; applied recursively to depth k it over-estimates at order h^(k+1), at the
cost of k + 1 sums and the closed form k orders higher. The first proved certificate (depth 1) failed at A = 100
by 1e-8 on five gaps because M3 at the flat atoms was over-estimated 20 to 500 times; depth 2 to 3 is what the
flat atoms need, which is why the tables go to order six.

What is and is not rigorous. Everything downstream of the decimal input (x_k, w_k as decimal strings) is
interval-enclosed: P and Q, log Q, log y!, every derivative; the y-sum truncation is bounded by tail_bound().
What this module does NOT make rigorous is the step from the decimal input, which satisfies the KKT
equalities only to its own residual (5e-16 for inputs stored as 17-digit floats), to an exact KKT point;
that is the audit's caveat 1 and the certificate reports it as the number eta rather than hiding it.
"""

import os, sys, json
from mpmath import iv, mp, mpf, mpi, loggamma, exp, log, nstr

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

# h_n = sum coef * u^i / x^j, entries (coef, i, j); generated by the recurrence in sympy (scratch gen_h.py)
H = {
    0: [(1, 0, 0)],
    1: [(-1, 0, 0), (1, 1, 0)],
    2: [(1, 0, 0), (-2, 1, 0), (-1, 1, 1), (1, 2, 0)],
    3: [(-1, 0, 0), (3, 1, 0), (3, 1, 1), (2, 1, 2), (-3, 2, 0), (-3, 2, 1), (1, 3, 0)],
    4: [
        (1, 0, 0),
        (-4, 1, 0),
        (-6, 1, 1),
        (-8, 1, 2),
        (-6, 1, 3),
        (6, 2, 0),
        (12, 2, 1),
        (11, 2, 2),
        (-4, 3, 0),
        (-6, 3, 1),
        (1, 4, 0),
    ],
    5: [
        (-1, 0, 0),
        (5, 1, 0),
        (10, 1, 1),
        (20, 1, 2),
        (30, 1, 3),
        (24, 1, 4),
        (-10, 2, 0),
        (-30, 2, 1),
        (-55, 2, 2),
        (-50, 2, 3),
        (10, 3, 0),
        (30, 3, 1),
        (35, 3, 2),
        (-5, 4, 0),
        (-10, 4, 1),
        (1, 5, 0),
    ],
    6: [
        (1, 0, 0),
        (-6, 1, 0),
        (-15, 1, 1),
        (-40, 1, 2),
        (-90, 1, 3),
        (-144, 1, 4),
        (-120, 1, 5),
        (15, 2, 0),
        (60, 2, 1),
        (165, 2, 2),
        (300, 2, 3),
        (274, 2, 4),
        (-20, 3, 0),
        (-90, 3, 1),
        (-210, 3, 2),
        (-225, 3, 3),
        (15, 4, 0),
        (60, 4, 1),
        (85, 4, 2),
        (-6, 5, 0),
        (-15, 5, 1),
        (1, 6, 0),
    ],
}
# c_n = coef / x^j
CC = {0: [], 1: [], 2: [(1, 1)], 3: [(-1, 2)], 4: [(2, 3)], 5: [(-6, 4)], 6: [(24, 5)]}
MAXORDER = 6


def _poly(order, u, xinv):
    """h_order(u, x) from the table; u and xinv may be intervals or mpf"""
    up = [1]
    xp = [1]
    for _ in range(order):
        up.append(up[-1] * u)
    for _ in range(order):
        xp.append(xp[-1] * xinv)
    s = 0
    for coef, i, j in H[order]:
        s = s + coef * up[i] * xp[j]
    return s


def _const(order, xinv):
    s = 0
    for coef, j in CC[order]:
        s = s + coef * xinv**j
    return s


class Channel:
    def __init__(self, A, xs, ws, dps=40, extra_ny=0):
        mp.dps = dps
        iv.dps = dps
        self.A = mpf(A)
        self.ny = int(float(A) + 18 * float(A) ** 0.5 + 50) + extra_ny
        self.LF = [iv.loggamma(iv.mpf(y + 1)) for y in range(self.ny)]
        self.LFp = [loggamma(y + 1) for y in range(self.ny)]

        # parameters may be decimal strings / floats (degenerate intervals) or intervals (a box around a
        # numerical KKT point, for the exact-point certificate); midpoints serve the sampling grids
        def as_iv(v):
            return (
                v
                if hasattr(v, "a") and hasattr(v, "b")
                else iv.mpf(v if isinstance(v, str) else repr(float(v)))
            )

        self.x = [as_iv(v) for v in xs]
        w = [as_iv(v) for v in ws]
        t = w[0]
        for v in w[1:]:
            t = t + v
        self.w = [v / t for v in w]
        self.K = len(xs)
        self.Q = []
        for y in range(self.ny):
            q = iv.mpf(0)
            for k in range(self.K):
                if self.x[k].a <= 0:
                    if y == 0:
                        q = q + self.w[k]
                else:
                    q = q + self.w[k] * self.P(self.x[k], y)
            self.Q.append(q)
        self.logQ = [iv.log(q) for q in self.Q]
        self.xp = [(mpf(v.a) + mpf(v.b)) / 2 for v in self.x]
        wp = [(mpf(v.a) + mpf(v.b)) / 2 for v in w]
        tp = sum(wp)
        self.wp = [v / tp for v in wp]
        self.Qp = [q.mid for q in self.Q]
        self.logQp = [log(q) for q in self.Qp]

    # ---- interval evaluation ----
    def L(self, X, y):
        return y * iv.log(X) - X - self.LF[y]

    def P(self, X, y):
        return iv.exp(self.L(X, y))

    def _sum(self, X, order):
        """naive interval enclosure of D^(order) over X"""
        if X.a <= 0:
            if X.a == X.b == 0 and order == 0:
                return -self.logQ[0]  # D(0) = -log Q(0), exactly
            raise ValueError("interval touches 0")
        xinv = 1 / X
        lX = iv.log(X)
        s = iv.mpf(0)
        for y in range(self.ny):
            Lv = y * lX - X - self.LF[y]
            p = iv.exp(Lv)
            g = Lv - self.logQ[y]
            s = s + p * _poly(order, y * xinv, xinv) * g
        return s + _const(order, xinv)

    def enclose(self, X, order, depth=2):
        """rigorous enclosure of D^(order) over X by the mean-value form applied recursively to the given depth"""
        if depth <= 0 or order + 1 > MAXORDER:
            return self._sum(X, order)
        a, b = mpf(X.a), mpf(X.b)
        if a == b:
            return self._sum(X, order)
        m = (a + b) / 2
        half = (b - a) / 2
        return self._sum(iv.mpf(m), order) + self.enclose(X, order + 1, depth - 1) * mpi(-half, half)

    def absmax(self, lo, hi, order, pieces=1, depth=2):
        """proved bound on max |D^(order)| over [lo, hi]"""
        best = mpf(0)
        for j in range(pieces):
            a = lo + (hi - lo) * mpf(j) / pieces
            b = lo + (hi - lo) * mpf(j + 1) / pieces
            v = self.enclose(mpi(a, b), order, depth)
            best = max(best, abs(mpf(v.a)), abs(mpf(v.b)))
        return best

    def D_iv(self, X):
        return self._sum(X, 0)

    def Dp_iv(self, X):
        return self._sum(X, 1)

    def Dpp_iv(self, X):
        return self._sum(X, 2)

    def Dppp_iv(self, X):
        return self._sum(X, 3)

    # ---- point evaluation (mpf), same closed forms ----
    def deriv(self, x, order):
        xinv = 1 / x
        lx = log(x)
        s = mpf(0)
        for y in range(self.ny):
            Lv = y * lx - x - self.LFp[y]
            if Lv < -400:
                continue
            s += exp(Lv) * _poly(order, y * xinv, xinv) * (Lv - self.logQp[y])
        return s + _const(order, xinv)

    def D(self, x):
        return self.deriv(x, 0)

    def Dp(self, x):
        return self.deriv(x, 1)

    def Dpp(self, x):
        return self.deriv(x, 2)

    def Dppp(self, x):
        return self.deriv(x, 3)

    def C_iv(self):
        c = iv.mpf(0)
        for k in range(self.K):
            if self.x[k].a <= 0:
                c = c + self.w[k] * (-self.logQ[0])
            else:
                c = c + self.w[k] * self.D_iv(self.x[k])
        return c

    def tail_bound(self, x_lo, order):
        """rigorous bound on the dropped tail sum_{y >= ny} P(x,y) |h_order| |g| for every x in [x_lo, A].
        For y >= ny > A: P(x,y) <= P(A,y), and P(A,y+1)/P(A,y) = A/(y+1) <= rho := A/ny < 1. For such y,
        w_A P(A,y) <= Q(y) <= P(A,y), so g = log P(x,y) - log Q(y) lies in [y log(x_lo/A), A + log(1/w_A)]
        and |g| <= max(A + log(1/w_A), y log(A/x_lo)). |h_order| <= sum |coef| (y/x_lo)^i / x_lo^j from the
        table. Every factor grows by at most (1 + 1/ny) per unit step in y beyond ny, so the summand is bounded
        by its value at ny times a geometric series with ratio rho (1 + 1/ny)^(order + 2)."""
        A = self.A
        ny = self.ny
        x_lo = mpf(x_lo)
        wA = mpf(self.w[-1].a)  # lower end, so the bound holds for every input in the box
        rho = A / ny
        rho2 = rho * (1 + mpf(1) / ny) ** (order + 2)
        if rho2 >= 1:
            return None
        PA = exp(ny * log(A) - A - loggamma(ny + 1))
        gb = max(A + log(1 / wA), ny * log(A / x_lo))
        hb = sum(abs(coef) * (ny / x_lo) ** i / x_lo**j for coef, i, j in H[order])
        return PA * hb * gb / (1 - rho2)


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    d = json.load(open(os.path.join(HERE, "results_q32_A100_mp2.json")))["11"]
    ch = Channel(100.0, d["x"], d["w"])
    from support_mp3 import _setup, _tables, D_of, Dp_of, Dpp_of

    ny = _setup(100.0, 40)
    xs = [mpf(repr(float(v))) for v in d["x"]]
    ws = [mpf(repr(float(v))) for v in d["w"]]
    t = sum(ws)
    ws = [v / t for v in ws]
    Pt, Qt = _tables(xs, ws, ny)

    print(
        "control 0: regenerate the tables from the recurrence (sympy) and compare with the hard-coded H, CC"
    )
    try:
        import sympy as sp
        from sympy.functions.combinatorial.numbers import stirling

        x, y, U, Xs = sp.symbols("x y U X", positive=True)
        u = y / x
        h = [sp.Integer(1)]
        for n in range(MAXORDER):
            h.append(sp.expand(sp.diff(h[-1], x) + h[-1] * (u - 1)))

        def E(expr):
            p = sp.Poly(sp.expand(expr), y)
            s = 0
            for (k,), c in p.terms():
                s += c * sum(stirling(k, j) * x**j for j in range(k + 1))
            return sp.simplify(s)

        c = [sp.Integer(0)]
        for n in range(MAXORDER):
            c.append(sp.simplify(E(h[n] * (u - 1)) + sp.diff(c[-1], x)))
        allok = True
        for n in range(MAXORDER + 1):
            e = sp.expand(sp.expand(h[n].subs(y, U * x)).subs(x, 1 / Xs))
            tab = sorted(
                [(int(cf), i, j) for (i, j), cf in sp.Poly(e, U, Xs).terms()], key=lambda t: (t[1], t[2])
            )
            ce = sp.expand(c[n].subs(x, 1 / Xs))
            ctab = sorted([(int(cf), j) for (j,), cf in sp.Poly(ce, Xs).terms()]) if ce != 0 else []
            ok = tab == H[n] and ctab == CC[n]
            allok = allok and ok
            print(
                f"   order {n}: h table {'matches' if tab == H[n] else 'DIFFERS'}, c {'matches' if ctab == CC[n] else 'DIFFERS'}"
            )
        print(f"   all tables match the recurrence: {allok}")
    except ImportError:
        print("   sympy not available; numeric checks only")

    print(
        "control 1: each closed form vs central difference of the previous order (h = 1e-12); order 2 vs support_mp3"
    )
    hh = mpf(10) ** -12
    for x in (mpf("0.7"), mpf(5), mpf(20), mpf(50), mpf(90)):
        line = f"   x = {float(x):5.1f} "
        line += f" D'' vs mp3 {nstr(abs(ch.Dpp(x) - Dpp_of(x, Qt, ny)), 2):>8}"
        for n in range(3, MAXORDER + 1):
            cf = ch.deriv(x, n)
            fd = (ch.deriv(x + hh, n - 1) - ch.deriv(x - hh, n - 1)) / (2 * hh)
            line += f"  D^({n}) {nstr(cf, 6):>12} diff {nstr(abs(cf - fd), 2):>8}"
        print(line)

    print("control 2: degenerate intervals contain the point values, orders 0..6")
    worst = mpf(0)
    wid = mpf(0)
    for x in (mpf("0.7"), mpf(20), mpf(90)):
        X = iv.mpf(x)
        for o in range(MAXORDER + 1):
            I = ch._sum(X, o)
            v = ch.deriv(x, o)
            worst = max(worst, mpf(I.a) - v, v - mpf(I.b))
            wid = max(wid, mpf(I.delta))
    print(f"   max distance outside {nstr(worst, 3)}   max width {nstr(wid, 3)}")

    print(
        "control 3: over-estimate (enclosure width minus true range) by depth, on cells of width 0.05 and 0.14; all must contain 50 samples"
    )
    for x0 in (mpf("0.7"), mpf(20), mpf(27)):
        for wdt in (mpf("0.05"), mpf("0.14")):
            X = mpi(x0, x0 + wdt)
            for o in (2, 3):
                vals = [ch.deriv(x0 + wdt * mpf(j) / 49, o) for j in range(50)]
                rng = max(vals) - min(vals)
                parts = []
                for depth in (0, 1, 2, 3):
                    I = ch.enclose(X, o, depth)
                    okc = all(mpf(I.a) <= v <= mpf(I.b) for v in vals)
                    parts.append(
                        f"d{depth} {nstr(mpf(I.delta) - rng, 2):>8}{'' if okc else ' NOT CONTAINED'}"
                    )
                print(
                    f"   [{float(x0):5.1f},+{float(wdt):.2f}] D^({o}) true range {nstr(rng, 2):>8}  |D^({o})| ~ {nstr(max(abs(v) for v in vals), 2):>8}   "
                    + "  ".join(parts)
                )
    print("control 4: tail bounds (orders 0..6) at x_lo = 1e-8 and 0.5")
    for xl in ("1e-8", "0.5"):
        print(
            f"   x_lo = {xl}: " + "  ".join(nstr(ch.tail_bound(mpf(xl), o), 2) for o in range(MAXORDER + 1))
        )
    Ci = ch.C_iv()
    print(f"C as interval: [{nstr(mpf(Ci.a), 30)}, {nstr(mpf(Ci.b), 30)}] width {nstr(mpf(Ci.delta), 3)}")
